# Generated by Django 3.0 on 2020-04-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppings',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prices',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
