# Generated by Django 3.0 on 2020-04-16 05:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200416_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 5, 42, 9, 684490, tzinfo=utc), verbose_name='Date Ordered'),
        ),
    ]
