# Generated by Django 3.0 on 2020-04-18 08:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200418_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzas',
            name='price',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 8, 33, 21, 896127, tzinfo=utc), verbose_name='Date Ordered'),
        ),
        migrations.DeleteModel(
            name='Prices',
        ),
    ]
