# Generated by Django 3.0.5 on 2020-05-03 21:01

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200418_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='content',
        ),
        migrations.AddField(
            model_name='orders',
            name='content',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 21, 1, 12, 640259, tzinfo=utc), verbose_name='Date Ordered'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.CharField(max_length=300),
        ),
    ]
